CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY ,
    username VARCHAR(200) NOT NULL ,
    email VARCHAR(254) NOT NULL ,
    password VARCHAR(50) NOT NULL
);
CREATE SEQUENCE user_id_sequence START WITH 3 INCREMENT BY 1;