DROP TABLE IF EXISTS users CASCADE;
DROP SEQUENCE IF EXISTS user_id_seq;
DROP TABLE IF EXISTS notes CASCADE;
DROP SEQUENCE IF EXISTS notes_id_seq;
DROP TABLE IF EXISTS directories CASCADE;
DROP SEQUENCE IF EXISTS directory_id_seq;
-- DROP SEQUENCE IF EXISTS hibernate_sequence;